# Generated by Django 4.1.7 on 2023-02-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(default='Nebulosa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
