# Generated by Django 4.1.7 on 2023-02-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publica',
            field=models.BooleanField(default=False),
        ),
    ]
