# Generated by Django 4.1.7 on 2023-02-21 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0010_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='favorito',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
