# Generated by Django 4.1.7 on 2023-02-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_fotografia_total_visualizações'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='total_visualizações',
            new_name='total_visualizacoes',
        ),
    ]
